services:
  postgres:
    image: postgres:17 
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: typeracer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: